@HOST = http://localhost:9000/api/v1/auth
### tk: admin@admin.com
### mk: hello123@
### sign up
POST {{HOST}}/signup
Content-Type: application/json

{
  "email":"baotrandinh.ute@gmail.com",
  "name":"bao tran",
  "nickName":"kuro",
  "gender":"male",
  "birthDay":"2000-12-04",
  "password":"hello123@"
}

### active account
GET {{HOST}}/signup/active?token=sdfsfsd

{}

### login
POST {{HOST}}/login
Content-Type: application/json

{
  "email":"admin@admin",
  "password":"hello123@"
}

### request register seller
GET {{HOST}}/seller/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDI3ZGZmOTY0MjIxNzU5NzYyZGNhZDAiLCJyb2xlIjoidXNlciIsInRpbWVDcmVhdGVkIjoxNjgwMzM0ODcwODgzLCJpYXQiOjE2ODAzMzQ4NzEsImV4cCI6MTY4MDMzODQ3MX0.2XoszoWonOIk_XYxx2gWQt0jBxLKJHv60HwGg9tHA9M

{}

### register seller
POST {{HOST}}/seller/create
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDI3ZGZmOTY0MjIxNzU5NzYyZGNhZDAiLCJpYXQiOjE2ODAzMzQ4ODYsImV4cCI6MTY4MDQyMTI4Nn0.i81glaUM4uWqjOemDLwFp7Lm9gE8aaczj4F8dOuJmwY",
  "name":"Test Shop",
  "phone":"0329460523",
  "address":[{
    "location":"12 dien bien phu"
  }],
  "logo":"agdasgdj",
  "slogan":"Just do it!"
}

### check token exists
GET {{HOST}}/token/check?token=175eceba-a36d-4aad-9fd5-1df3476048c2

### send email reset password
POST {{HOST}}/password/email
Content-Type: application/json

{
  "email":"baotrandinh.ute@gmail.com"
}

### reset password by token
POST {{HOST}}/password/reset
Content-Type: application/json

{
  "token":"b142514a-7a3f-4ed1-baa9-bf91f8df178a",
  "password":"123bao@@45"
}

### refresh token
POST {{HOST}}/login/refresh
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDA2YjM5NDJkOGZkNjZmZjViZTc1ODAiLCJyb2xlIjoidXNlciIsImlhdCI6MTY3ODMyNTk5MiwiZXhwIjoxNjc4MzI5NTkyfQ.gk9gpC9mouvljaY7SItSbtJcjq06vtWBWs_h8sRWsBo"
}

### google login
POST {{HOST}}/oauth/google
Content-Type: application/json

{
  
}

