@HOST=http://localhost:8000/api/v1/category

POST {{HOST}}/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDI3ZGYxODMxNDc3MjhkMGVlYTU0NjQiLCJyb2xlIjoiYWRtaW4iLCJ0aW1lQ3JlYXRlZCI6MTY4MDMzNTA3MDc5MCwiaWF0IjoxNjgwMzM1MDcwLCJleHAiOjE2ODAzMzg2NzB9.NUlDp7LumPL6oDrpZBvJ5_o5V2ZskGnqYuwy06GXHCU

{
  "name":"Comedi"
}

### get all categories
GET {{HOST}}/all
Content-Type: application/json

{}

### get all category with amount
GET {{HOST}}/all-amount
Content-Type: application/json

{}

### get sellers
GET http://localhost:8000/api/v1/sellers

### get top 3 sellers
GET http://localhost:8000/api/v1/sellers/top3