@HOST=http://localhost:8000/api/v1

@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYwOTBhOTJkZjdhN2RhOGUyZTk1ZWEiLCJyb2xlIjoidXNlciIsInRpbWVDcmVhdGVkIjoxNjg0OTYwNjExODkxLCJpYXQiOjE2ODQ5NjA2MTIsImV4cCI6MTY4NDk2NDIxMn0.FT4ZL6Zv_rMliB1dc3bts3_gES0rXSWT4j3a5j2vuBo

### login
POST {{HOST}}/auth/login
Content-Type: application/json

{
  "email":"test01@yopmail.com",
  "password":"hello123@"
}

## seller login
##user02@gmail.com

### add order
//note: shipping code set to default :(((
POST {{HOST}}/order/add
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "order":{
    "addressId":"64667f7b905d463cda72008b",
    "paymentType": "cod",
    "items":[
      {
        "productId":"6461db631a8f4bca357fc087",
        "quantity":5,
        "variant": "6463987828c09d6e9471f0b3",
        "shippingCode": 1
    },
      {
        "productId":"6456a1173d40716d5ffcdbfd",
        "quantity":5,
        "variant":"6456a1173d40716d5ffcdbfe",
        "shippingCode":1
      }
    ]

  }
}

### get order not done by seller
GET {{HOST}}/order/seller/not-done?page=1&limit=8
Authorization: Bearer {{Token}}

### get all order by user
GET {{HOST}}/order/all
Authorization: Bearer {{Token}}

### get all order packed by user
GET {{HOST}}/order/all-packed
Authorization: Bearer {{Token}}

### get all ordered by user
GET {{HOST}}/order/all-ordered
Authorization: Bearer {{Token}}

### get all ordered cancelled by user
GET {{HOST}}/order/all-cancelled
Authorization: Bearer {{Token}}

### get all order shipping by shipper
GET {{HOST}}/order/shipper/get-order
Authorization: Bearer {{Token}}

### update status order
PUT {{HOST}}/order/shipper/update-order
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "orderItemId": "646a1c9ee79958393dc1d295"
}

### cancel orderItemId by shipper
PUT {{HOST}}/order/shipper/cancel-order
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "orderItemId": "",
  "reason": ""
}

### reject orderItemId by user
PUT {{HOST}}/order/shipper/reject-order
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "orderItemId":"",
  "reason":""
}

### get all order done by seller
GET {{HOST}}/order/seller/done
Authorization: Bearer {{Token}}

### get all order completed by user
GET {{HOST}}/order/all-done
Authorization: Bearer {{Token}}

### review by user
POST {{HOST}}/product/user/review
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "productId":"6461db631a8f4bca357fc084",
  "rating":5,
  "comment":"The nice book, you should try it!"
}