@HOST=http://localhost:9000/api/v1/product

### add product
POST {{HOST}}/add
Content-Type: application/json
Authorization: Bearer 

{
  "name":"product 1",
  "quantity":1000,
  "maxOrder":123,
  "price":125,
  "discountPercent":12,
  "summary":"ashgd",
  "description":"jghasd",
  "category":"ashgd",
  "productPictures":[],
}